/**
 * Progressive-enhancement list filter, shared by /work and /insights.
 *
 * Filtering is CSS: the script only sets data-filter-active on the root, and
 * rules generated by FilterBar.astro hide non-matching items. With JS off the
 * bar stays hidden and every item stays visible.
 */

const ALL = 'all';

function initRoot(root: HTMLElement): void {
  const param = root.dataset.filterParam;
  const bar = root.querySelector<HTMLElement>('[data-filter-bar]');
  const count = root.querySelector<HTMLElement>('[data-filter-count]');
  if (!param || !bar || !count) return;

  const buttons = Array.from(bar.querySelectorAll<HTMLButtonElement>('[data-filter-value]'));
  const items = Array.from(root.querySelectorAll<HTMLElement>('[data-filter-values]'));
  const valid = new Set(buttons.map((b) => b.dataset.filterValue));

  const apply = (value: string, announce: boolean) => {
    if (value === ALL) delete root.dataset.filterActive;
    else root.dataset.filterActive = value;

    for (const button of buttons) {
      button.setAttribute('aria-pressed', String(button.dataset.filterValue === value));
    }

    const shown =
      value === ALL
        ? items.length
        : items.filter((i) => i.dataset.filterValues?.split(' ').includes(value)).length;
    // Only announce on a user action; a silent initial state avoids noise on load.
    if (announce) {
      count.textContent = (count.dataset.template ?? '{shown} of {total}')
        .replace('{shown}', String(shown))
        .replace('{total}', String(items.length));
    }
  };

  const fromUrl = new URL(window.location.href).searchParams.get(param);
  apply(fromUrl && valid.has(fromUrl) ? fromUrl : ALL, false);
  bar.hidden = false;

  for (const button of buttons) {
    button.addEventListener('click', () => {
      const value = button.dataset.filterValue ?? ALL;
      apply(value, true);
      const url = new URL(window.location.href);
      if (value === ALL) url.searchParams.delete(param);
      else url.searchParams.set(param, value);
      // Keep the router's history state so view transitions still work on back/forward.
      history.replaceState(history.state, '', url);
    });
  }
}

export function initFilters(): void {
  document.querySelectorAll<HTMLElement>('[data-filter-root]').forEach(initRoot);
}
